import React from "react";
import { Container, Row, Col } from 'react-bootstrap';
import ProjectCard from "../Card/ProjectCard";
import img1 from '../../assets/blud.png'; // Correct path
import img2 from '../../assets/atm.png'; // Correct path
import img3 from '../../assets/workout.png'; // Correct path

export default function Projects() {
    return (
        <Container>
            <Row className="custom-font text-center">
                <h2>Check out some of my projects!</h2>
            </Row>
            <Row>
                <Col md={4}>
                    <ProjectCard 
                        cardTitle="BLUD"
                        cardImage={img1}
                        bodyText="Embark on an action-packed journey with two characters as they uncover the perilous secrets of the criminal underworld in our multiplayer platformer puzzle game."
                        buttonText="Devpost"
                        href="https://devpost.com/software/blud"
                    />
                </Col>
                <Col md={4}>
                    <ProjectCard 
                        cardTitle="ATM Authenticator"
                        cardImage={img2}
                        bodyText="ATM Authenticator offers the future of secure banking by integrating Three-Factor-Authentication into current ATM software, allowing for fingerprint scans and one-time codes generated by mobile banking apps."
                        buttonText="Devpost"
                        href="https://devpost.com/software/atm-authenticator"
                    />
                </Col>
                <Col md={4}>
                    <ProjectCard 
                        cardTitle="Workout Tracker"
                        cardImage={img3}
                        bodyText="Workout tracking application incorporated with user-friendly features such as the ability to customize reps, sets, weight, and add/remove workouts, as well as set workout reminders."
                        buttonText="GitHub"
                        href="https://github.com/sillycelery/workout-tracker-react"
                    />
                </Col>
            </Row>
        </Container>
    );
}
